trigger:
  - main

pool:
  name: 'mag-pool'

steps:
  # Install Node.js in the frontend
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  # Install dependencies for the frontend
  - task: Npm@1
    displayName: "Installing dependencies for frontend"
    inputs:
      command: 'install'
      workingDir: 'frontend'

  # Build the frontend
  - task: Npm@1
    displayName: "Building frontend"
    inputs:
      command: 'custom'
      customCommand: 'run build'
      workingDir: 'frontend'

  # Install dependencies for the backend
  - task: Npm@1
    displayName: "Installing dependencies for backend"
    inputs:
      command: 'install'
      workingDir: 'backend'

  # Copy build artifacts
  - task: CopyFiles@2
    inputs:
      contents: |
        frontend/build/**
        backend/**
      targetFolder: $(Build.ArtifactStagingDirectory)

  # Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'release'
      publishLocation: 'Container'
